language: node_js
before_script:
  - gem install bourbon
  - npm install -g gulp
  - npm install gulp
  - npm install
cache:
  directories:
    - node_modules 
script: 
  - gulp sass
  - gulp jade
  - gulp compile-js
